
#' Add exposure information to the top of the table
#'
#' Add exposure information such as total number of subjects and years of
#' exposure
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param exposure data.frame with the exposure information to add
#' @param ... rename columns
#' @param format_alone \code{logical} Should the exposure be formatted alone or
#'   together with the column it is assigned to
#' @param format_data A vector or data.frame specifying the format for each
#'   variable
#'
#' @return An object of class \code{NNTable} with the exposure data added
#' @export
#'
#' @examples
#' ## *****************************************************************************
#' ## # Calculate summary statistics                                           ----
#' ##
#' ## The exposure/summary statistics are calculated for ADSL and ADLB
#' ## *****************************************************************************
#'
#' # filter and rename adsl to get totals
#' library(dplyr)
#'
#' adsl_f <- adsl       %>%
#' filter(FASFL == "Y") %>%
#'   rename(TRTP = TRT01P)
#'
#' # calculate the totals by treatment arm
#' totals <- adsl_f         %>%
#'   mutate(TRTP = "Total") %>%
#'   bind_rows(adsl_f)      %>%
#'   filter(FASFL == "Y")   %>%
#'   group_by(TRTP)         %>%
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#'
#' # Calculate the summary statistcs
#' output <- adlb                                                  %>%
#'   mutate(TRTP = "Total")                                        %>%
#'   bind_rows(adlb)                                               %>%
#'   filter(SAFFL == "Y" & PARAMCD %in% c("ABSR148N", "ABTIT148")) %>%
#'   group_by(TRTP, PARAM, STUDYID)                                %>%
#'   summarize(N  = n_distinct(USUBJID),
#'             Mean = mean(AVAL, na.rm = TRUE),
#'             SD   = sd(  AVAL, na.rm = TRUE),
#'             Min  = min( AVAL, na.rm = TRUE),
#'             Max  = max( AVAL, na.rm = TRUE)
#'   )
#'
#' # The NNTable is generated in small steps to view what happens
#'
#' # Initiate the table
#' .NNTable <- NNTable(output, "PARAM", "TRTP", "N", "Mean (SD)", "Min ; Max")
#'
#' # View the table
#' .NNTable
#'
#'
#' # Transpose the summary columns to long format
#' .NNTable <- .NNTable                                    %>%
#'   addTransLong(SUM = c("N", "Mean (SD)" , "Min ; Max"),
#'                var_name = "Called var")                 %>%
#'   addFormat(format_data = c(N = "%.0f"), dec = 2)
#'
#' # View the table
#' .NNTable
#'
#' # Add exposure, transpose to wide and ad grouping variables
#' .NNTable <- addExposure(.NNTable, exposure = totals,
#'                         format_alone = TRUE,
#'                         format_data  = c("Number of subjects" = "%.0f")) %>%
#'             addTransWide(TRTP = "SUM")                                   %>%
#'             addGroupedColumns("PARAM", "Called var")
#'
#' # View the final result
#' .NNTable
addExposure <- function(.NNTable,
                        exposure, ...,
                        format_alone = FALSE,
                        format_data = NULL) {

  if (!is.null(format_data)) {
    if (!is.data.frame(format_data)) {
      format_data <- as.data.frame(t(format_data), )
    }
    factors <- sapply(format_data, is.factor)
    if (length(factors))
      format_data[, factors] <- lapply(format_data[, factors], as.character)
  }

  .NNTable$exposure <- list(data = exposure,
                            rename = c(...),
                            format_alone = format_alone,
                            format_data  = format_data)

  return(.NNTable)
}


applyExposure <- function(.NNTable) {

  # Get the exposure
  if (!is.null(.NNTable$exposure$data_trans)) {
    exposure <- .NNTable$exposure$data_trans
  } else {
    exposure <- .NNTable$exposure$data
  }


  # Get the data
  data_str <- .NNTable$data_str

  # Add a new order variable to the data sets
  data_str$NNTable_mj_order <- 1
  exposure$NNTable_mj_order <- 0

  # get the class of each variable in data_str
  classes <- sapply(data_str, class)
  classes_ord <- classes[unlist(.NNTable$concat$table)]


  # find free columns ----
  left_over <- unlist(sapply(.NNTable$tree$tree, function(x) if (is.atomic(x)) x))
  left_over_columns <- .NNTable$columns[names(left_over)]

  classes <- sapply(data_str, class)

  by_temp <- names(classes)[classes %in% c("factor", "character")]
  stable <- intersect(left_over_columns, by_temp)


  if (is.null(.NNTable$columns_to_long) || length(.NNTable$columns_to_long) == 0) {
    # Find the columns not in data
    new_cols <- setdiff(colnames(exposure), colnames(data_str))

    # find the name column
    # The name column is the first character column

    if (is.null(.NNTable$grouped_columns)) {
      names_to <- names(classes_ord[names(classes_ord) %in% stable])[1]
    } else {
      names_to <- .NNTable$grouped_columns$columns[length(.NNTable$grouped_columns$columns)]
    }

    # Get the value column ---------------------------------------------------
    # if any to wide columns are used it needs to b taken into account
    if (!is.null(.NNTable$columns_to_wide$columns)) {

      getNames_to_wide <- function(list, names = c()) {
        if (is.recursive(list)) {
          names <- c(names, names(list))
          return(getNames_to_wide(list[[1]], names))
        }

        return(names)
      }

      trans_cols <- getNames_to_wide( .NNTable$columns_to_wide$columns)

      if (any(trans_cols %in% colnames(exposure))) {
        if (!(all(trans_cols %in% colnames(exposure)))) {
          missing_cols <- setdiff(trans_cols, colnames(exposure))
          stop(paste("The columns", paste(missing_cols, collapse = ", "),
                     "are missing from the exposure dataset"))
        }

        possibs <- unlist(.NNTable$concat$table[initName(.NNTable$columns_to_wide$columns)])
        values_to <- possibs[classes_ord[possibs] %in% c("integer", "numeric")][1]
      }

    } else {
      values_to <- names(classes_ord[classes_ord %in% c("integer", "numeric")][1])
    }

    # Pivot the data to match the data_str format
    exposure <- tidyr::pivot_longer(exposure, cols = all_of(new_cols),
                                    names_to = unlist(names_to), values_to = values_to)

    # Pivot the format data similarly
    format_data <- .NNTable$exposure$format_data
    if (!is.null(.NNTable$exposure$format_data))
      format_data <- tidyr::pivot_longer(.NNTable$exposure$format_data, cols = new_cols,
                                          names_to = unlist(names_to), values_to = values_to)

  } else {

    # Find the columns not in data
    new_cols <- setdiff(colnames(exposure), colnames(data_str))


    # add the columns to the columns data of the table
    .NNTable$columns <- c(.NNTable$columns, structure(new_cols, names = new_cols))

    # the new columns are added to the transpose to long columns
    add_elements <- function(list, new_cols) {
      if (is.recursive(list))
        list[[1]] <- add_elements(list[[1]], new_cols)
      else
        return(c(new_cols, list))
      return(list)
    }

    .NNTable$columns_to_long$columns <-
      add_elements(.NNTable$columns_to_long$columns, new_cols)

    .NNTable <- get_columns(.NNTable, new_data = data_str)

    format_data <- .NNTable$exposure$format_data
  }

  # Add the new order column to the remove columns
  .NNTable$remove$columns <- c(.NNTable$remove$columns, "NNTable_mj_order", "NNTable_exposure_data")

  # Combine the data and update .NNTable
  .NNTable$data_str <- dplyr::bind_rows(exposure, data_str) %>%
    dplyr::mutate(NNTable_exposure_data = dplyr::case_when(.data$NNTable_mj_order == 0 ~ TRUE, TRUE ~ FALSE))

  # update collapse columns
  if (!(is.null(.NNTable$columns_to_long) || length(.NNTable$columns_to_long) == 0))
    .NNTable <- get_columns(.NNTable, new_data = .NNTable$data_str)

  # Add  the order variable to the current order vars
  .NNTable$order_columns$columns <-
    unique(c("NNTable_mj_order", .NNTable$order_columns$columns))


  # Handling of Formatting ------------------------------------------------------

  # if format alone is desired we add NNTable_mj_order to group_by
  group_by <- .NNTable$NNFormat$group_by
  if (.NNTable$exposure$format_alone) {
    group_by <-
      unique(c("NNTable_mj_order", .NNTable$NNFormat$group_by))
  }

  # dependent on whether or not we have added formatting in the first place it
  # is re-applied
  if (is.null(.NNTable$NNFormat)) {
    .NNTable <-
      addFormat(.NNTable, group_by = group_by, format_data = format_data)
  } else {
    .NNTable$NNFormat$group_by <- group_by

    if (!is.null(format_data) && !is.null(.NNTable$NNFormat$format_data)) {

      if (length(intersect(colnames(format_data),
                           colnames(.NNTable$NNFormat$format_data))) |
          nrow(.NNTable$NNFormat$format_data) != 1 | nrow(format_data) != 1) {

        format_comb <- dplyr::bind_rows(format_data, .NNTable$NNFormat$format_data)

      } else {
        format_comb <- dplyr::bind_cols(format_data, .NNTable$NNFormat$format_data)
      }
      .NNTable$NNFormat$format_data <- format_comb
    }
  }

  # return the modified NNTable object
  return(.NNTable)
}
