#' Add specifications to the width beteen columns
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#'   should the leading space be discarded
#' @param spread \code{logical} Should the columns be spread out to fill the page width
#' @param max.sep \code{integer} indicating maximum with between regular columns
#' @param max.space \code{integer} indicating maximum with between grouped columns
#' @param sep \code{integer} indicating the width of the separators between columns
#' @param space \code{integer} indicating the width of the separation between grouped columns
#'
#' @return An object of class \code{NNTable} with the page split added
#'
#' @export

addSpaceControl <- function(.NNTable,
                            spread = TRUE,
                            max.sep = 50, max.space = 50,
                            sep = 1, space = 1) {

  .NNTable$spacing <- list(
    spread    = spread,
    max.sep   = max.sep,
    max.space = max.space,
    sep       = sep,
    space     = space)

  .NNTable
}
