#' Add translations to an NNTable
#'
#' Sometimes the values in data are not very informative and needs to be translated,
#' e.g. for SEX: "Female" instead of "F" and "Male" instead of "M".
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param ... the columns in data that needs to be translated. e.g
#'   \code{SEX = c("Male" = "M", "Female" = "F")} will replace \code{"M"} by \code{"Male"}.
#'   Alternatively, it is possible to pass a function, e.g. to transform column
#'   \code{AESOC} to title case  \code{"AESOC" = stringr::str_to_title}.
#'   The column names should be the original column names and should not
#'   reflect any renaming.
#'
#'
#' @return An object of class \code{NNTable} with the columns translated
#' @examples
#' library(NNR)
#' library(NNBiostat)
#'
#' # make sure the training data is up to date
#' NNtraining::createTrainingDB()
#' (db <- nnaccess("0001", root = "~/training"))
#'
#' adae_f <- db$adam("adae") %>% filter(SAFFL == "Y" & TRTA != "")
#' adsl_f <- db$adam("adsl") %>% filter(SAFFL == "Y" & TRT30A != "") %>%
#'   rename(TRTA = TRT30A)
#'
#'
#' subjects <- adsl_f %>%
#'   group_by(TRTA, SEX) %>%
#'   summarise("Number of subjects" = n_distinct(USUBJID),
#'             "Total exposure" = sum(TRDURY),
#'             .groups = "drop")
#'
#' subjects$SEX <- as.factor(subjects$SEX)
#'
#'
#' stats <- adae_f %>%
#'   group_by(TRTA,AESOC,SEX) %>%
#'   summarise(N = n_distinct(USUBJID),
#'             E = n(), .groups = "drop")
#'
#' stats$SEX <- as.factor(stats$SEX)
#
#' table <- NNTable(stats, "TRTA", Sex = "SEX", "AESOC","N","E") %>%
#'   addTransWide("TRTA" = c("N","E")) %>%
#'   addGroupedColumns("AESOC") %>%
#'   addOrder(E = -1)
#'
#' # print the table
#' table
#'
#' # we would like to rename some values to make the content more clear
#' table %>%
#'   addTranslate(TRTA  = c("Ico" = "A", "NOVO rapid" = "B"),
#'                SEX   = c("Female" = "F", "Male" = "M"),
#'                AESOC = stringr::str_to_title)
#'
#' @export
addTranslate <-  function(.NNTable, ...) {

  .NNTable$translations <- list(...)

  return(.NNTable)
}


#' @importFrom forcats fct_recode
#' @importFrom glue glue
apply_tanslation <- function(.NNTable) {

  translations <- .NNTable$translations

  data_str <- .NNTable$data_str

  if (!is.null(.NNTable$exposure)) {
    .NNTable$exposure$data_trans <- translator(.NNTable$exposure$data, translations)
  }

  .NNTable$data_str <- translator(.NNTable$data_str, translations)

  .NNTable
}


translator <- function(data, translations) {

  translations[setdiff(names(translations), colnames(data))] <- NULL

  args <- translations
  for (i in seq_along(translations)) {


    if (is.character(translations[[i]])) {

      if (is.character(data[[names(translations)[i]]])) {
        case_1 <- paste(paste0('`', names(translations)[i],'` == "', translations[[i]], '"~"', names(translations[[i]]), '"' ), collapse = ", ")

        case_2 <- paste(case_1, glue::glue(", TRUE ~ `{names(translations)[i]}`"))

        args[[names(translations)[i]]] <- rlang::parse_expr(glue::glue("case_when({case_2})"))
      } else if (is.factor(data[[names(translations)[i]]])) {

        case_1 <- paste(paste0(names(translations[[i]]), ' = "', translations[[i]], '"'), collapse = ", ")

        args[[names(translations)[i]]] <- rlang::parse_expr(glue::glue("fct_recode(`{names(translations)[i]}`, {case_1})"))
      }

    } else if (is.function(translations[[i]])) {

      args[[names(translations)[i]]] <- rlang::parse_expr(glue::glue("translations[[{i}]](`{names(translations)[i]}`)"))
    }
  }

  do.call(dplyr::mutate, c(list(.data = data), args))
}
