
#' Add columns that needs to be transposed from wide to long
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param ... \code{character} or \code{list} specifying the columns to
#'   transpose.The names of the character will be the names displayed in the
#'   table when transposed to long.
#' @param value_name \code{character} with the name of the value column
#' @param var_name \code{character} with the name of the name column
#' @param display_name The display name of the name column
#' @param remove_blank \code{logical} Should blank rows be deleted. If only some
#'   should be deleted add a space to the specific row and column combination
#'
#' @return An object of class \code{NNTable} with the transpose specified
#'
#' @export
#'
#' @examples
#'
#' ## *****************************************************************************
#' ## # Calculate summary statistics                                           ----
#' ##
#' ## The exposure/summary statistics are calculated for ADSL and ADLB
#' ## *****************************************************************************
#'
#' # filter and rename adsl to get totals
#' # library(NNR)
#' library(dplyr)
#'
#' adsl_f <- adsl       %>%
#' filter(FASFL == "Y") %>%
#'   rename(TRTP = TRT01P)
#'
#' # calculate the totals by treatment arm
#' totals <- adsl_f         %>%
#'   mutate(TRTP = "Total") %>%
#'   bind_rows(adsl_f)      %>%
#'   filter(FASFL == "Y")   %>%
#'   group_by(TRTP)         %>%
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#'
#' # Calculate the summary statistcs
#' output <- adlb                                                  %>%
#'   mutate(TRTP = "Total")                                        %>%
#'   bind_rows(adlb)                                               %>%
#'   filter(SAFFL == "Y" & PARAMCD %in% c("ABSR148N", "ABTIT148")) %>%
#'   group_by(TRTP, PARAM, STUDYID)                                %>%
#'   summarize(N  = n_distinct(USUBJID),
#'             Mean = mean(AVAL, na.rm = TRUE),
#'             SD   = sd(  AVAL, na.rm = TRUE),
#'             Min  = min( AVAL, na.rm = TRUE),
#'             Max  = max( AVAL, na.rm = TRUE)
#'   )
#'
#' # The NNTable is generated in small steps to view what happens
#'
#' # Initiate the table
#' .NNTable <- NNTable(output, "PARAM", "TRTP", "N", "Mean (SD)", "Min ; Max")
#'
#' # View the table
#' .NNTable
#'
#'
#' # Transpose the summary columns to long format
#' .NNTable <- .NNTable                                    %>%
#'   addTransLong(SUM = c("N", "Mean (SD)" , "Min ; Max"),
#'                var_name = "Called var")                 %>%
#'   addFormat(format_data = c(N = "%.0f"), dec = 2)
#'
#' # View the table
#' .NNTable
#'
#' # Add exposure, transpose to wide and ad grouping variables
#' .NNTable <- addExposure(.NNTable, exposure = totals,
#'                         format_alone = TRUE,
#'                         format_data  = c("Number of subjects" = "%.0f")) %>%
#'             addTransWide(TRTP = "SUM")                                   %>%
#'             addGroupedColumns("PARAM", "Called var")
#'
#' # View the final result
#' .NNTable
#'
#' @importFrom methods missingArg
#' @importFrom data.table ':=' setnames
addTransLong <- function(.NNTable, ...,
                         value_name,
                         var_name = "name",
                         display_name,
                         remove_blank = TRUE) {

  # ensure that columns is a list
  columns <- list(...)

  if (methods::missingArg(value_name)) {
    if (!is.null(names(columns)))
      value_name <- names(columns)
    else value_name <- "value"
  }

  names(columns) <- value_name

  if (missingArg(display_name))
    display_name <- var_name

  .NNTable$columns_to_long <-
    list(columns = columns, value_name = value_name, var_name = var_name,
         display_name = display_name, remove_blank = remove_blank)

  return(.NNTable)
}

apply_tranToLong <- function(.NNTable) {


  #Create a data.table
  data <- data.table::as.data.table(.NNTable$data_str)


  # retrieve the columns
  columns <- .NNTable$columns_to_long$columns

  # create the value name
  if (.NNTable$columns_to_long$value_name != "") {
    value = .NNTable$columns_to_long$value_name
  } else {
    value = "value"
  }

  # create a current order variable
  data$orig_order_to_delte <- seq_len(nrow(data))

  # reshape the data
  out <- data.table::melt(data, measure.vars  = columns,
                          value.name = value, variable.name = "Group")


  # if remove blanks is set to TRUE blank rows are removed
  if (.NNTable$columns_to_long$remove_blank)
    out <- out[out[[value]] != "", ]


  # if colums vector is named, the names are used for the group names
  group_names <- initName(columns)
  if (!is.null(names(group_names))) {
    new_names = structure(names(group_names),
                          names = group_names)

    out <- out[ , Group := factor(new_names[unlist(out[, Group])], levels = new_names)]
  } else {
    out <- out[ , Group := factor(unlist(out[, Group]), levels = group_names)]
  }

  # order according to the original variable
  out <- out[order(orig_order_to_delte)]
  out <- out[, orig_order_to_delte := NULL]

  # Rename the group column to the supplied name
  out <- data.table::setnames(out, old = "Group", new = .NNTable$columns_to_long$var_name)


  # Replace the string data set
  .NNTable$data_str <- as.data.frame(out)

  # Return the updated NNTable
  return(.NNTable)
}


