
#' Add underscore to an NNTable header
#'
#' @param .NNTable  An \code{NNTable} generated by
#'   \code{\link{NNTable}}
#' @param add \code{logical} indicating whether the underscore should be added
#'
#' @return An object of class \code{NNTable} where underscores will be made in
#'   the header
#' @export
addUnderScore <- function(.NNTable, add = TRUE) {
  .NNTable$header <- list(underscore = add)

  return(.NNTable)
}
