#' Add wrapping to an NNTable
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param title \code{character} with the title
#' @param footnote \code{character} with the footnote
#' @param sys_footnote \code{character} with the system footnote
#' @param title_space \code{character} to be added between the title and
#'   and table header
#' @param footer_space \code{character} to be added between the footnote and
#'   sys_footnote.
#'
#' @return An object of class \code{NNTable} with the wrapping specified
#' @export
#'
#' @importFrom stringi stri_wrap
#' @examples
#'
#' ## *****************************************************************************
#' ## # Example of transpose from wide to long                                 ----
#' ##
#' ## Calculate the statistics for an AE table
#' ## *****************************************************************************
#'
#' library(dplyr)
#' # library(NNR)
#'
#' # Filter data according Safety analysis set
#' adsl_f <- adsl            %>%
#'   filter(SAFFL == "Y")    %>%
#'     rename(TRTA = TRT01P)
#'
#' # Calculate total exposure
#' totals <- adsl_f        %>%
#'   group_by(TRTA)        %>%
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#'
#' # Calculate adverse event statistics
#' output <- adae %>% group_by(AEBODSYS, AEDECOD, TRTA) %>%
#'   dplyr::summarise(N = n_distinct(USUBJID),
#'                    P = N / nrow(adsl),
#'                    E = n())
#'
#' # Generate the NNTable ------------------------------------------------------
#'
#' # Initiate by defining the columns based on ADAE
#' .NNTable <- NNTable(output, "AEBODSYS", "AEDECOD", "TRTA", "N", "(%)" = "(P)", "E") %>%
#'             addTruncation(AEBODSYS = 50, AEDECOD = 48)                              %>%
#'             addGroupedColumns("AEBODSYS", "AEDECOD" , name = "some name")
#'
#' # Add the title and footnote, these can span several lines and will
#' #  automatically be wrapped
#' .NNTable <- .NNTable %>%
#'             addWrapping(title        = "This could be a very long title",
#'                         footnote     = "This could be a very long footnote",
#'                         sys_footnote = "Explain where the data comes from")
#'
#' # View the final result
#' .NNTable
addWrapping <- function(.NNTable, title, footnote, sys_footnote, title_space = "", footer_space = "") {

  width <- .NNTable$page_size$page.width

  # Add the title
  title <- stringi::stri_wrap(title, width = width, simplify = TRUE)
  title <- c(title, title_space)

  footer <- stringi::stri_wrap(footnote, width = width, simplify = TRUE)
  footer <- c(footer, footer_space)

  sys_footnote <- stringi::stri_wrap(sys_footnote, width = width, simplify = TRUE)

  .NNTable$wrapping <- list(title = title, footer = footer, sys_footnote = sys_footnote)

  return(.NNTable)
}


