#' Add wrapping to an NNTable
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param title \code{character} with the title
#' @param footnote \code{character} with the footnote
#' @param sys_footnote \code{character} with the system footnote
#' @param title_space \code{character} to be added between the title and
#'   and table header
#' @param footer_space \code{character} to be added between the footnote and
#'   sys_footnote.
#'
#' @return An object of class \code{NNTable} with the wrapping specified
#' @export
#'
#' @importFrom stringi stri_wrap
#' @examples
#'
#' ## *****************************************************************************
#' ## # Example of transpose from wide to long                                 ----
#' ##
#' ## Calculate the statistics for an AE table
#' ## *****************************************************************************
#'
#' library(dplyr)
#' # library(NNR)
#'
#' # Filter data according Safety analysis set
#' adsl_f <- adsl            %>%
#'   filter(SAFFL == "Y")    %>%
#'     rename(TRTA = TRT01P)
#'
#' # Calculate total exposure
#' totals <- adsl_f        %>%
#'   group_by(TRTA)        %>%
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#'
#' # Calculate adverse event statistics
#' output <- adae %>% group_by(AEBODSYS, AEDECOD, TRTA) %>%
#'   dplyr::summarise(N = n_distinct(USUBJID),
#'                    P = N / nrow(adsl),
#'                    E = n())
#'
#' # Generate the NNTable ------------------------------------------------------
#'
#' # Initiate by defining the columns based on ADAE
#' .NNTable <- NNTable(output, "AEBODSYS", "AEDECOD", "TRTA", "N", "(%)" = "(P)", "E") %>%
#'             addTruncation(AEBODSYS = 50, AEDECOD = 48)                              %>%
#'             addGroupedColumns("AEBODSYS", "AEDECOD" , name = "some name")
#'
#' # Add the title and footnote, these can span several lines and will
#' #  automatically be wrapped
#' .NNTable <- .NNTable %>%
#'             addWrapping(title        = "This could be a very long title",
#'                         footnote     = "This could be a very long footnote",
#'                         sys_footnote = "Explain where the data comes from")
#'
#' # View the final result
#' .NNTable
addWrapping <- function(.NNTable, title, footnote, sys_footnote, title_space = "", footer_space = "") {

  .NNTable$wrapping <- list(title_orig        = title,
                            footer_orig       = footnote,
                            sys_footnote_orig = sys_footnote,
                            title_space       = title_space,
                            footer_space      = footer_space)
  return(.NNTable)
}


apply_width_wrapping <- function(.NNTable) {

  width <- .NNTable$page_size$page.width

  title  <- .NNTable$wrapping$title_orig
  footer <- .NNTable$wrapping$footer_orig
  sys_footnote <- .NNTable$wrapping$sys_footnote_orig

  # Add the title
  if (.NNTable$print_method$type != "txt") {

    caption <- stringWrap(title, width = width, font_size = 11)
    .NNTable$wrapping$caption <- caption

    title  <- stringWrap(title, width = width, font_size = .NNTable$font_size)
    footer <- stringWrap(footer, width = width, font_size = .NNTable$font_size)
    sys_footnote <- stringWrap(sys_footnote, width = width, font_size = .NNTable$font_size)
    auto_foot <- sys_footnote
  } else {
    title  <- stringi::stri_wrap(title, width = width, simplify = TRUE)
    footer <- stringi::stri_wrap(footer, width = width, simplify = TRUE)
    sys_footnote <- stringi::stri_wrap(sys_footnote, width = width, simplify = TRUE)
    auto_foot <- alignRight(c(sys_footnote, ""), width = .NNTable$page_size$page.width)
  }

  title <- c(title, .NNTable$wrapping$title_space)
  footer <- c(footer, .NNTable$wrapping$footer_space)

  .NNTable$wrapping$title <- title
  .NNTable$wrapping$footer <- footer
  .NNTable$wrapping$sys_footnote <- sys_footnote

  .NNTable$wrapping$auto_foot <- auto_foot

  return(.NNTable)
}


apply_n_bodylines <- function(.NNTable) {

  #---------------------------------------------------------------------------#
  ######                        lines calculation                        ######
  #---------------------------------------------------------------------------#

  if (.NNTable$print_method$type == "txt") {

    # Calculate title lines
    title.lines <- max(1, length(.NNTable$wrapping[["title"]]))

    # calculate the number of header lines
    header.lines <- 2 + length(.NNTable$header$header)

    # calculate footer lines
    footer.lines <- 1 + max(1, length(.NNTable$wrapping[["footer"]])) + 1 +
      max(0, length(.NNTable$wrapping[["sys_footnote"]]))

     # body lines
    .NNTable$page_size$body.lines <- .NNTable$page_size$page.length - (title.lines + header.lines + footer.lines)
    .NNTable$page_size$body.lines.page1 <- .NNTable$page_size$body.lines
    .NNTable$page_size$body.lines.page2 <- .NNTable$page_size$body.lines

  } else {
    #---------------------------------------------------------------------------#
    ######                   Calculate table height                        ######
    #---------------------------------------------------------------------------#


    caption_height <-
      stringHeightAdj(paste(c(unlist(.NNTable$wrapping$caption)), collapse = "\n"),
                      font_size = 11, font_type = 2) +
      stringHeightAdj("M", font_size = 10, font_type = 1)


    title_height <-
      stringHeightAdj(paste(c(unlist(.NNTable$wrapping$title), "", ""), collapse = "\n"),
                      font_size = .NNTable$font_size)



    footer_height <-
      stringHeightAdj(paste(c(unlist(.NNTable$wrapping$footer),
                              unlist(.NNTable$wrapping$sys_footnote)), collapse = "\n"),
                      font_size = .NNTable$font_size)


    footer_height <- footer_height +
      sum((c(unlist(.NNTable$wrapping$footer), unlist(.NNTable$wrapping$sys_footnote)) == "") *
            stringHeightAdj("M", font_size = .NNTable$font_size)) * 0.25

    height_page1 <- .NNTable$page_size$page.length -
      (caption_height + footer_height)

    height_page2 <- .NNTable$page_size$page.length -
      (title_height + footer_height)



    cell_height <- stringHeightAdj("M", font_size = .NNTable$font_size)


    n.lines_page1 <- floor(height_page1 / cell_height)
    n.lines_page2 <- floor(height_page2 / cell_height)


    #---------------------------------------------------------------------------#
    ######                  subtract header lines                          ######
    #---------------------------------------------------------------------------#

    if (.NNTable$header$underscore) {
      n_header_lines <- ceiling(nrow(.NNTable$header$matrix) / 2)
    } else {
      n_header_lines <- nrow(.NNTable$header$matrix)
    }

    .NNTable$page_size$body.lines <- n.lines_page1 - n_header_lines

    .NNTable$page_size$body.lines.page1 <- n.lines_page1 - n_header_lines
    .NNTable$page_size$body.lines.page2 <- n.lines_page2 - n_header_lines
    .NNTable$page_size$cell_height <- cell_height
  }


  .NNTable
}



