#' Add formatting info to an NNTable
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param dec \code{integer} defining the number of decimals to use
#' @param format_data \code{data.frame} containing a set of formats. The column
#'   names of the supplied data to \code{\link{NNTable}} will be matched to the
#'   column names of \code{format_data}.
#' @param big.mark \code{character} for thousands Separator
#' @param small.mark \code{character} for Separating each fifth decimal
#' @param ... Additional arguments, not currently supported
#' @param group_by \code{character} with golumns indicating groups by which the
#'   format is calculated individually
#'
#' @return An object of class \code{NNTable} with the formatting applied
#' @export
#' @examples
#' ## *****************************************************************************
#' ## # Calculate summary statistics                                           ----
#' ##
#' ## The exposure/summary statistics are calculated for ADSL and ADLB
#' ## *****************************************************************************
#'
#' # filter and rename adsl to get totals
#' # library(NNR)
#' library(dplyr)
#'
#' adsl_f <- adsl       %>%
#' filter(FASFL == "Y") %>%
#'   rename(TRTP = TRT01P)
#'
#' # calculate the totals by treatment arm
#' totals <- adsl_f         %>%
#'   mutate(TRTP = "Total") %>%
#'   bind_rows(adsl_f)      %>%
#'   filter(FASFL == "Y")   %>%
#'   group_by(TRTP)         %>%
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#'
#' # Calculate the summary statistcs
#' output <- adlb                                                  %>%
#'   mutate(TRTP = "Total")                                        %>%
#'   bind_rows(adlb)                                               %>%
#'   filter(SAFFL == "Y" & PARAMCD %in% c("ABSR148N", "ABTIT148")) %>%
#'   group_by(TRTP, PARAM, STUDYID)                                %>%
#'   summarize(N  = n_distinct(USUBJID),
#'             Mean = mean(AVAL, na.rm = TRUE),
#'             SD   = sd(  AVAL, na.rm = TRUE),
#'             Min  = min( AVAL, na.rm = TRUE),
#'             Max  = max( AVAL, na.rm = TRUE)
#'   )
#'
#' # The NNTable is generated in small steps to view what happens
#'
#' # Initiate the table
#' .NNTable <- NNTable(output, "PARAM", "TRTP", "N", "Mean (SD)", "Min ; Max")
#'
#' # View the table
#' .NNTable
#'
#'
#' # Transpose the summary columns to long format
#' .NNTable <- .NNTable                                    %>%
#'   addTransLong(SUM = c("N", "Mean (SD)" , "Min ; Max"),
#'                var_name = "Called var")                 %>%
#'   addFormat(format_data = c(N = "%.0f"), dec = 2)
#'
#' # View the table
#' .NNTable
#'
#' # Add exposure, transpose to wide and ad grouping variables
#' .NNTable <- addExposure(.NNTable, exposure = totals,
#'                         format_alone = TRUE,
#'                         format_data  = c("Number of subjects" = "%.0f")) %>%
#'             addTransWide(TRTP = "SUM")                                   %>%
#'             addGroupedColumns("PARAM", "Called var")
#'
#' # View the final result
#' .NNTable
addFormat <- function(.NNTable, dec = 3, format_data = NULL, 
                      big.mark = "", small.mark = "", group_by = NULL, ...) {

  if (!is.null(format_data)) {
    if (!is.data.frame(format_data)) {
      format_data <- as.data.frame(t(format_data), )
    }
    factors <- sapply(format_data, is.factor)
    if (length(factors))
      format_data[, factors] <- lapply(format_data[, factors], as.character)
  }

  .NNTable$NNFormat <- list(dec         = dec,
                            format_data = format_data,
                            big.mark    = big.mark,
                            small.mark  = small.mark,
                            group_by    = group_by)
  
  return(.NNTable)
}


#' Add alignment specifications to an .NNTable
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param ... The alignment specification. It can be specified as: some_col1 =
#'   "c", "some with col2" = "l", some_col3 = "r", where some_col1, "some with
#'   col2", and some_col3 corresponds to the column names in the original data.
#'   When used together with \code{link{addTranLong}} the created column names
#'   need to be used.


#' @return An object of class \code{NNTable} with the formatting applied
#' @export
#' @examples
#' ## *****************************************************************************
#' ## # Example of transpose from wide to long                                 ----
#' ##
#' ## Calculate the statistics for an AE table  
#' ## *****************************************************************************
#'  
#' library(dplyr)
#' # library(NNR)
#' 
#' # Filter data according Safety analysis set
#' adsl_f <- adsl            %>% 
#'   filter(SAFFL == "Y")    %>% 
#'     rename(TRTA = TRT01P)
#' 
#' # Calculate total exposure 
#' totals <- adsl_f        %>% 
#'   group_by(TRTA)        %>% 
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#' 
#' # Calculate adverse event statistics
#' output <- adae %>% group_by(AEBODSYS, AEDECOD, TRTA) %>%
#'   dplyr::summarise(N = n_distinct(USUBJID),
#'                    P = N / nrow(adsl),
#'                    E = n())
#'   
#' # Generate the NNTable ------------------------------------------------------
#' 
#' # Initiate by defining the columns based on ADAE
#' .NNTable <- NNTable(output, "AEBODSYS", "AEDECOD", "TRTA", "N", "(%)" = "(P)", "E") 
#' 
#' # Add exposure calculated from ADSL
#' .NNTable <- .NNTable %>% 
#'   addExposure(exposure = totals, 
#'               format_alone = FALSE, 
#'               format_data  = c("Number of subjects"     = "%.0f", 
#'                                "Total exposure (years)" = "%.2f"))
#' 
#' # Test alignment                               
#' .NNTable <- .NNTable %>% addAlignment(AEDECOD = "c", AEBODSYS = "r")
#'   
#' # print the table
#' .NNTable
addAlignment <- function(.NNTable, ...) {
  .NNTable$alignment <- list(alignment_specified = c(...))
  
  return(.NNTable)
  
}


#' Add filling to an NNTable
#'
#' @param .NNTable An \code{NNTable} generated by
#'   \code{\link{NNTable}}
#' @param ... Named elements where the name is the column and value is the
#'   inserted value
#' @param by \code{character} defining the columns the fillings should be added
#'   in accordance to. Missing combinations of the by columns will be added for
#'   the columns defined in \code{columns}.
#'
#' @return An object of class \code{NNTable} with the filling specified
#' @export
#' @examples 
#' 
#' ## *****************************************************************************
#' ## # Example of transpose from wide to long                                 ----
#' ##
#' ## Calculate the statistics for an AE table  
#' ## *****************************************************************************
#'  
#' library(dplyr)
#' # library(NNR)
#' 
#' # Filter data according Safety analysis set
#' adsl_f <- adsl            %>% 
#'   filter(SAFFL == "Y")    %>% 
#'     rename(TRTA = TRT01P)
#' 
#' # Calculate total exposure 
#' totals <- adsl_f        %>% 
#'   group_by(TRTA)        %>% 
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#' 
#' # Calculate adverse event statistics
#' output <- adae %>% group_by(AEBODSYS, AEDECOD, TRTA) %>%
#'   dplyr::summarise(N = n_distinct(USUBJID),
#'                    P = N / nrow(adsl),
#'                    E = n())
#'   
#' # Generate the NNTable ------------------------------------------------------
#' 
#' # Initiate by defining the columns based on ADAE
#' .NNTable <- NNTable(output, "AEBODSYS", "AEDECOD", "TRTA", "N", "(%)" = "(P)", "E") 
#' 
#' # Add exposure calculated from ADSL
#' .NNTable <- .NNTable %>% 
#'   addExposure(exposure = totals, 
#'               format_alone = FALSE, 
#'               format_data  = c("Number of subjects"     = "%.0f", 
#'                                "Total exposure (years)" = "%.2f"))
#'  
#' # Transpose to wide  
#' .NNTable <- .NNTable %>% addTransWide(TRTA = c("N", "(%)", "E"))
#' 
#' # Add Filling such that non-observed events is assigned 0 
#' .NNTable <- .NNTable %>% addFilling(N = 0)
#' 
#' # Add formatting information for the table
#' .NNTable <- .NNTable %>% addFormat(format_data = c(N = "%.0f", P = "%.2f", E = "%.0f"))
#' 
#' # Group the columns AEBODSYS and AEDECOD
#' .NNTable <- .NNTable %>% addGroupedColumns("AEBODSYS", "AEDECOD" , name = "some name")
#' 
#' # Truncate columns at a certain width such that long names appear on multiple lines 
#' .NNTable <- .NNTable %>% addTruncation(AEBODSYS = 50, AEDECOD = 48) 
#' 
#' # View the final result
#' .NNTable
addFilling <- function(.NNTable, ..., by = NULL) {
  
  .NNTable$filling <- list(columns = c(...), by = by)

  return(.NNTable)
}



#' Add wrapping to an NNTable
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param title \code{character} with the title
#' @param footnote \code{character} with the footnote
#' @param sys_footnote \code{character} with the system footnote
#' @param title_space \code{character} to be added between the title and
#'   and table header
#' @param footer_space \code{character} to be added between the footnote and
#'   sys_footnote.
#'
#' @return An object of class \code{NNTable} with the wrapping specified
#' @export
#'
#' @importFrom stringi stri_wrap
#' @examples 
#' 
#' ## *****************************************************************************
#' ## # Example of transpose from wide to long                                 ----
#' ##
#' ## Calculate the statistics for an AE table  
#' ## *****************************************************************************
#'  
#' library(dplyr)
#' # library(NNR)
#' 
#' # Filter data according Safety analysis set
#' adsl_f <- adsl            %>% 
#'   filter(SAFFL == "Y")    %>% 
#'     rename(TRTA = TRT01P)
#' 
#' # Calculate total exposure 
#' totals <- adsl_f        %>% 
#'   group_by(TRTA)        %>% 
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#' 
#' # Calculate adverse event statistics
#' output <- adae %>% group_by(AEBODSYS, AEDECOD, TRTA) %>%
#'   dplyr::summarise(N = n_distinct(USUBJID),
#'                    P = N / nrow(adsl),
#'                    E = n())
#'   
#' # Generate the NNTable ------------------------------------------------------
#' 
#' # Initiate by defining the columns based on ADAE
#' .NNTable <- NNTable(output, "AEBODSYS", "AEDECOD", "TRTA", "N", "(%)" = "(P)", "E") %>% 
#'             addTruncation(AEBODSYS = 50, AEDECOD = 48)                              %>% 
#'             addGroupedColumns("AEBODSYS", "AEDECOD" , name = "some name")
#'  
#' # Add the title and footnote, these can span several lines and will 
#' #  automatically be wrapped             
#' .NNTable <- .NNTable %>% 
#'             addWrapping(title        = "This could be a very long title",
#'                         footnote     = "This could be a very long footnote",
#'                         sys_footnote = "Explain where the data comes from")           
#'  
#' # View the final result
#' .NNTable
addWrapping <- function(.NNTable, title, footnote, sys_footnote, title_space = "", footer_space = "") {

  width <- .NNTable$page_size$page.width

  # Add the title
  title <- stringi::stri_wrap(title, width = width, simplify = TRUE)
  title <- c(title, title_space)

  footer <- stringi::stri_wrap(footnote, width = width, simplify = TRUE)
  footer <- c(footer, footer_space)

  sys_footnote <- stringi::stri_wrap(sys_footnote, width = width, simplify = TRUE)

  .NNTable$wrapping <- list(title = title, footer = footer, sys_footnote = sys_footnote)

  return(.NNTable)
}


#' Add columns that needs to be transposed from wide to long
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param ... \code{character} or \code{list} specifying the columns to
#'   transpose.The names of the character will be the names displayed in the
#'   table when transposed to long.
#' @param value_name \code{character} with the name of the value column
#' @param var_name \code{character} with the name of the name column
#' @param display_name The display name of the name column
#' @param remove_blank \code{logical} Should blank rows be deleted. If only some
#'   should be deleted add a space to the specific row and column combination
#'
#' @return An object of class \code{NNTable} with the transpose specified
#'
#' @export
#' 
#' @examples 
#' 
#' ## *****************************************************************************
#' ## # Calculate summary statistics                                           ----
#' ##
#' ## The exposure/summary statistics are calculated for ADSL and ADLB
#' ## *****************************************************************************
#' 
#' # filter and rename adsl to get totals
#' # library(NNR)
#' library(dplyr)
#' 
#' adsl_f <- adsl       %>% 
#' filter(FASFL == "Y") %>% 
#'   rename(TRTP = TRT01P)
#' 
#' # calculate the totals by treatment arm
#' totals <- adsl_f         %>% 
#'   mutate(TRTP = "Total") %>%
#'   bind_rows(adsl_f)      %>%
#'   filter(FASFL == "Y")   %>% 
#'   group_by(TRTP)         %>% 
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#' 
#' # Calculate the summary statistcs
#' output <- adlb                                                  %>% 
#'   mutate(TRTP = "Total")                                        %>%
#'   bind_rows(adlb)                                               %>% 
#'   filter(SAFFL == "Y" & PARAMCD %in% c("ABSR148N", "ABTIT148")) %>% 
#'   group_by(TRTP, PARAM, STUDYID)                                %>% 
#'   summarize(N  = n_distinct(USUBJID),
#'             Mean = mean(AVAL, na.rm = TRUE),
#'             SD   = sd(  AVAL, na.rm = TRUE),
#'             Min  = min( AVAL, na.rm = TRUE),
#'             Max  = max( AVAL, na.rm = TRUE)
#'   )
#' 
#' # The NNTable is generated in small steps to view what happens
#' 
#' # Initiate the table 
#' .NNTable <- NNTable(output, "PARAM", "TRTP", "N", "Mean (SD)", "Min ; Max")
#' 
#' # View the table
#' .NNTable
#' 
#' 
#' # Transpose the summary columns to long format
#' .NNTable <- .NNTable                                    %>%
#'   addTransLong(SUM = c("N", "Mean (SD)" , "Min ; Max"), 
#'                var_name = "Called var")                 %>% 
#'   addFormat(format_data = c(N = "%.0f"), dec = 2)
#' 
#' # View the table
#' .NNTable
#' 
#' # Add exposure, transpose to wide and ad grouping variables
#' .NNTable <- addExposure(.NNTable, exposure = totals, 
#'                         format_alone = TRUE, 
#'                         format_data  = c("Number of subjects" = "%.0f")) %>% 
#'             addTransWide(TRTP = "SUM")                                   %>% 
#'             addGroupedColumns("PARAM", "Called var")
#'             
#' # View the final result
#' .NNTable
#'
#' @importFrom methods missingArg
#' @importFrom data.table ':=' setnames
addTransLong <- function(.NNTable, ..., 
                         value_name, 
                         var_name = "name", 
                         display_name,
                         remove_blank = TRUE) {

  # ensure that columns is a list
  columns <- list(...)

  if (methods::missingArg(value_name)) {
    if (!is.null(names(columns)))
      value_name <- names(columns)
    else value_name <- "value"
  }

  names(columns) <- value_name

  if (missingArg(display_name))
    display_name <- var_name

  .NNTable$columns_to_long <-
    list(columns = columns, value_name = value_name, var_name = var_name, 
         display_name = display_name, remove_blank = remove_blank)

  return(.NNTable)
}


#' Add columns that needs to be transposed from long to wide
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param ... Nested \code{list} of columns that should be transposed. For one
#'   level it can be defined as TRTA = c("N", "P", "E")xx. Nested levels are
#'   added in lists (sex = list(TRTA = c("N", "P", "E"))
#' @param add_cat_space \code{logical} indicating if a category spacer should be
#'   added
#' @param fun.aggregate \code{function} if more than one value is present in
#'   data for each grouping this function will be used to summarise
#' @param .remove_last_header_row \code{logical} indicating if the last header
#'   row should be removed in case only one sublevel is present for each column
#' @param .remove_empty_columns \code{logical} indicating if created columns
#'   that are completely empty should be removed.
#' @param .remove_empty_level \code{integer} indicating the level from which
#'   empty nested columns are removed. A value of 1 indicates that all empty
#'   columns should be removed. A value of 2 indicates that all columns in level
#'   1 should be empty before the columns are removed.
#'
#' @return An object of class \code{NNTable} with the transpose specified
#'
#' @examples
#'
#' ## *****************************************************************************
#' ## # Example of transpose from wide to long                                 ----
#' ##
#' ## Calculate the statistics for an AE table
#' ## *****************************************************************************
#'
#' library(dplyr)
#' #library(NNR)
#'
#' # Filter data according Safety analysis set
#' adsl_f <- adsl            %>%
#'   filter(SAFFL == "Y")    %>%
#'     rename(TRTA = TRT01P)
#'
#' # Calculate total exposure
#' totals <- adsl_f        %>%
#'   group_by(TRTA)        %>%
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#'
#' # Calculate adverse event statistics
#' output <- adae %>% group_by(AEBODSYS, AEDECOD, TRTA) %>%
#'   dplyr::summarise(N = n_distinct(USUBJID),
#'                    P = N / nrow(adsl),
#'                    E = n())
#'
#' # Generate the NNTable ------------------------------------------------------
#'
#' # Initiate by defining the columns based on ADAE
#' .NNTable <- NNTable(output, "AEBODSYS", "AEDECOD", "TRTA", "N", "(%)" = "(P)", "E")
#'
#' # Add exposure calculated from ADSL
#' .NNTable <- .NNTable %>%
#'   addExposure(exposure = totals,
#'               format_alone = FALSE,
#'               format_data  = c("Number of subjects"     = "%.0f",
#'                                "Total exposure (years)" = "%.2f"))
#'
#' # Transpose to wide
#' .NNTable <- .NNTable %>% addTransWide(TRTA = c("N", "(%)", "E"))
#'
#' # Add Filling such that non-observed events is assigned 0
#' .NNTable <- .NNTable %>% addFilling(N = 0)
#'
#' # Add formatting information for the table
#' .NNTable <- .NNTable %>% addFormat(format_data = c(N = "%.0f", P = "%.2f", E = "%.0f"))
#'
#' # Group the columns AEBODSYS and AEDECOD
#' .NNTable <- .NNTable %>% addGroupedColumns("AEBODSYS", "AEDECOD" , name = "some name")
#'
#' # Truncate columns at a certain width such that long names appear on multiple lines
#' .NNTable <- .NNTable %>% addTruncation(AEBODSYS = 50, AEDECOD = 48)
#'
#' # View the final result
#' .NNTable
#'
#' ## *****************************************************************************
#' ## # Example of transpose from with newsted columns                         ----
#' ##
#' ## Calculate the statistics for an AE table grouped by age group
#' ## *****************************************************************************
#' # create summary
#' output <- adae %>% group_by(AGEGR2, AEBODSYS, AEDECOD, TRTA) %>%
#'   dplyr::summarise(N = n_distinct(USUBJID),
#'                    P = N / nrow(adsl) * 100,
#'                    E = n())
#'
#' # create the NNTable
#' .NNTable <- NNTable(output, "AGEGR2", "AEBODSYS", "AEDECOD", "TRTA", "N", "(%)" = "(P)", "E") %>%
#'   addTransWide(AGEGR2 = list(TRTA = c("N", "(%)", "E"))) %>%
#'   addFilling(N = 0) %>%
#'   addGroupedColumns("AEBODSYS", "AEDECOD") %>%
#'   addTruncation(AEBODSYS = 32, AEDECOD = "30") %>%
#'   addOrder(N = -1)
#'
#' .NNTable
#'
#' # change the order of the transpose
#' .NNTable %>% addTransWide(TRTA = list(AGEGR2 = c("N", "(%)", "E")))
#'
#' @export
addTransWide <- function(.NNTable, ..., .remove_last_header_row = TRUE, 
                         .remove_empty_columns = TRUE,
                         .remove_empty_level = 1,
                         add_cat_space = TRUE, fun.aggregate = c) {
  columns <- list(...)
  .NNTable$columns_to_wide <- list(columns = columns, add_cat_space = add_cat_space,
                                  fun.aggregate = fun.aggregate,
                                  .remove_last_header_row = .remove_last_header_row,
                                  .remove_empty_columns = .remove_empty_columns,
                                  .remove_empty_level = .remove_empty_level)
  
  return(.NNTable)
}


NNtable_group_add_names <- function(group_cols, invisible, add_blank_row, 
                                    add_blank_row_when, add_blank_row_invisible) {
  
  if (is.logical(add_blank_row)) {
    
    if (add_blank_row) {
      
      add_blank_row <- group_cols[-1]
      
      if (!add_blank_row_invisible)
        add_blank_row <- setdiff(add_blank_row, invisible)
      
    } else {
      add_blank_row <- character(0)
    }
  }
  
  if (is.null(names(add_blank_row))) {
    add_blank_row <- structure(rep(add_blank_row_when, length(add_blank_row)), names = add_blank_row)
  } else {
    if (any(names(add_blank_row) == "")) {
      blank_names <- names(add_blank_row)
      blank_names[blank_names == ""] <- add_blank_row[blank_names == ""]
      
      named_vec <- structure(add_blank_row, names = blank_names)
      named_vec[names(add_blank_row) == "" ] <- add_blank_row_when
      add_blank_row <- named_vec 
    }
  }
  
  return(add_blank_row)
}


#' Add grouped columns to an NNTable
#'
#' @param .NNTable An \code{NNTable} generated by \code{\link{NNTable}}
#' @param ... elements with the names of the columns to group
#' @param name \code{character} with the name of grouping column
#' @param add_blank_row \code{logical} Add a blank line between every grouping.
#'   Alternative \code{character} with the column names of the group columns for
#'   which a blank should be added. Alternatively, it can be a \code{character}
#'   specifying which grouping columns should have a blank added, the grouping
#'   name can be assigned a value of either \code{"missing"} or \code{"always"}
#'   which overrules \code{add_blank_row_when}.
#' @param span_row \code{logical} should group columns span the entire row
#' @param invisible \code{character} Grouped columns that should not be
#'   displayed
#' @param add_blank_row_invisible \code{logical} should blank rows be added for
#'   invisible columns. Note, that this is an additional empty row compared to
#'   the header row that is blank. Ignored if \code{add_blank_row} is a
#'   character.
#' @param add_header_rows_invisible \code{logical} Should a blank header row be
#'   added to invisible grouped columns. Alternative, \code{character} with
#'   invisible groups that should have a blank header.
#' @param add_blank_row_when \code{character}, if set equal to \code{"missing"}
#'   blank rows are only added when an group header is missing, i.e. if the
#'   header is supplied in the data no blank row is added. When set equal to
#'   \code{always} it is added regardless of the group header was supplied in
#'   the data.
#'
#' @return An object of class \code{NNTable} with the column grouping specified
#' @export
#' @examples
#'
#' ## *****************************************************************************
#' ## # Example of transpose from wide to long                                 ----
#' ##
#' ## Calculate the statistics for an AE table
#' ## *****************************************************************************
#'
#' library(dplyr)
#' # library(NNR)
#'
#' # Filter data according Safety analysis set
#' adsl_f <- adsl            %>%
#'   filter(SAFFL == "Y")    %>%
#'     rename(TRTA = TRT01P)
#'
#' # Calculate total exposure
#' totals <- adsl_f        %>%
#'   group_by(TRTA)        %>%
#'   summarize("Number of subjects"     = n_distinct(USUBJID),
#'             "Total exposure (years)" = sum(TR01DURY))
#'
#' # Calculate adverse event statistics
#' output <- adae %>% group_by(AEBODSYS, AEDECOD, TRTA) %>%
#'   dplyr::summarise(N = n_distinct(USUBJID),
#'                    P = N / nrow(adsl),
#'                    E = n())
#'
#' # Generate the NNTable ------------------------------------------------------
#'
#' # Initiate by defining the columns based on ADAE
#' .NNTable <- NNTable(output, "AEBODSYS", "AEDECOD", "TRTA", "N", "(%)" = "(P)", "E")
#'
#' # Add exposure calculated from ADSL
#' .NNTable <- .NNTable %>%
#'   addExposure(exposure = totals,
#'               format_alone = FALSE,
#'               format_data  = c("Number of subjects"     = "%.0f",
#'                                "Total exposure (years)" = "%.2f"))
#'
#' # Transpose to wide
#' .NNTable <- .NNTable %>% addTransWide(TRTA = c("N", "(%)", "E"))
#'
#' # Add Filling such that non-observed events is assigned 0
#' .NNTable <- .NNTable %>% addFilling(N = 0)
#'
#' # Add formatting information for the table
#' .NNTable <- .NNTable %>% addFormat(format_data = c(N = "%.0f", P = "%.2f", E = "%.0f"))
#'
#' # Group the columns AEBODSYS and AEDECOD
#' .NNTable <- .NNTable %>% addGroupedColumns("AEBODSYS", "AEDECOD" , name = "some name")
#'
#' # Truncate columns at a certain width such that long names appear on multiple lines
#' .NNTable <- .NNTable %>% addTruncation(AEBODSYS = 50, AEDECOD = 48)
#'
#' # View the final result
#' .NNTable
#' 
addGroupedColumns <- function(.NNTable, ..., name = "", invisible = character(0),
                              span_row = TRUE, 
                              add_blank_row = TRUE, 
                              add_blank_row_when = c("missing", "always"),
                              add_blank_row_invisible  = FALSE,
                              add_header_rows_invisible = TRUE) {
  
  add_blank_row_when <- match.arg(add_blank_row_when)
  columns <- c(...)
  
  add_blank_row <- 
    NNtable_group_add_names(group_cols = columns, 
                            invisible, add_blank_row, 
                            add_blank_row_when, 
                            add_blank_row_invisible)
  

  .NNTable$grouped_columns <- list(columns = columns, name = name, 
                                   span_row = span_row, 
                                   add_blank_row = add_blank_row,
                                   add_blank_row_when = add_blank_row_when,
                                   add_blank_row_invisible = add_blank_row_invisible,
                                   add_header_rows_invisible = add_header_rows_invisible,
                                   invisible = invisible)

  .NNTable$remove$columns <- c(.NNTable$remove$columns, "NNTable_master_group", columns, "NNTable_added_blank", "NNTable_added_group", "NNTable_group_level")

  return(.NNTable)
}


#' Add underscore to an NNTable header
#'
#' @param .NNTable  An \code{NNTable} generated by
#'   \code{\link{NNTable}}
#' @param add \code{logical} indicating whether the underscore should be added
#'
#' @return An object of class \code{NNTable} where underscores will be made in
#'   the header
#' @export
addUnderScore <- function(.NNTable, add = TRUE) {
  .NNTable$header <- list(underscore = add)
  
  return(.NNTable)
}
